# -*- coding: utf-8 -*-
"""gen_semi_RF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16h5D30QUWITsxsbfrdpTBLlQ9gO-q0Si
"""

import librosa
from IPython.display import Audio
import matplotlib.pyplot as plt

import torch
import numpy as np
from skimage import data
from skimage.color import rgb2gray
import torch
import torch.nn.functional as F
import torch.nn as nn
import skimage.measure
import csv
import pandas as pd
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(torch.cuda.device_count())

data_type = 'audio'

if data_type == 'audio':
  #path of the audio file
  audio_data = 'flutesample.wav'
  audio_guitar = 'data_music_only_guitar.wav'
  audio_violin = 'violin.wav'
  #This returns an audio time series as a numpy array 
  flute,sr = librosa.load(audio_data, sr=3000)
  guitar,sr = librosa.load(audio_guitar, sr=3000)
  violin,sr = librosa.load(audio_violin, sr=3000)
  print(flute.shape,guitar.shape) #,violin.shape)
  plt.plot(flute,'.')
  plt.plot(guitar,'.')
  plt.plot(violin,'.')
  x0 = torch.Tensor([flute[0:50],guitar[0:50],violin[0:50]]).to(device)
  print(x0.shape)
  np.savetxt('data.csv', x0, delimiter=',')
  Audio(flute,rate=sr)

else:
  mnist = pd.read_csv("/generatedmnist1/data_dress.csv")
  data = mnist.values[:,:]
  print(data.shape)
  x0 = torch.Tensor(data[:10,:]).to(device)
  for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(data[i,:].reshape(28,28),cmap=plt.cm.gray)
  # x0 = torch.tensor([x_new1.reshape(-1)/np.linalg.norm(x_new1),x_new2.reshape(-1)/np.linalg.norm(x_new2)]).to(device)

plt.figure(figsize=(10,3))

plt.subplot(1,2,1)
plt.plot(x0.cpu().detach().numpy()[0,:],'.')


plt.subplot(1,2,2)
plt.plot(x0.cpu().detach().numpy()[1,:],'.')


plt.show()

Audio(x0.cpu()[0,:],rate=sr)



n_steps = 100 # number of denoising time steps #,flute[3500:4000]])
d = x0.shape[1]
m = x0.shape[0]

alphas = (1. - torch.linspace(0.0001, 0.02, n_steps)).to(device)
alphas_cumprod = torch.cumprod(alphas, axis=0).to(device)

sqrt_alphas_cumprod = torch.sqrt(alphas_cumprod).to(device)
sqrt_one_minus_alphas_cumprod = torch.sqrt(1 - sqrt_alphas_cumprod ** 2).to(device)

def q_sample(x_0, t, noise):
    """
    Sample x at time t given the value of x at t=0 and the noise
    """
    return sqrt_alphas_cumprod.gather(-1, t).repeat(d,1).T * x_0 + sqrt_one_minus_alphas_cumprod.gather(-1, t).repeat(d,1).T  * noise

for t in [1, n_steps // 10, n_steps // 2, n_steps - 1]:
    noised_x = q_sample(x0, torch.tensor(t).to(device), torch.randn(1,d).to(device))
    print(noised_x.shape)
    plt.plot(noised_x.cpu().detach().numpy().reshape(-1),'.',label=f"t={t}")
plt.legend()
plt.show()


N = 80

class DenoiseModel(nn.Module):
    def __init__(self,num_in, num_out,n_steps):
        super(DenoiseModel, self).__init__()
        self.num_out = num_out
        self.lin = nn.Linear(num_in, num_out)
        self.embed = nn.Embedding(n_steps, num_out)
        self.lin3 = nn.Linear(num_out, num_in,bias = False) #,bias = False)



    def forward(self, x, y):
        z = torch.sin(self.lin(x))
        gamma = self.embed(y).reshape(y.shape[0],1,N)
        out = torch.cos(gamma) * z
        return self.lin3(out)

# class DenoiseModel(nn.Module):
#     def __init__(self,num_in, num_out):
#         super(DenoiseModel, self).__init__()
#         self.num_out = num_out
#         self.lin1 = nn.Linear(num_in, num_out)
#         self.lin2 = nn.Linear(num_in, num_out)
#         self.lin3 = nn.Linear(num_out, num_in,bias = False) #,bias = False)



#     def forward(self, x,y):
#         z = torch.sin(self.lin1(x))
#         gamma = self.lin2(x).reshape(z.shape[0],z.shape[1],N)
#         out = gamma * z
#         return self.lin3(out)

def p_loss(x, t):
    # Generate a noise
    # Compute x at time t with this value of the noise - forward process
    noisy_x = torch.zeros([t.shape[0],m,d]).to(device)
    noise = torch.randn(t.shape[0],m,d).to(device)
    t = t.to(device)
    for i in range(m):
      for j in range(t.shape[0]):
        #print(t[j])
        noisy_x[j,i,:] = q_sample(x[i,:], t[j], noise[j,i,:])
    # Use our trained model to predict the value of the noise, given x(t) and t
    noise_computed = denoise(noisy_x, t)
    # print(noise_computed.shape)
    return F.mse_loss(noise, noise_computed)


# denoise = DenoiseModel(d,N,n_steps).to(device)
denoise = DenoiseModel(d,N,100).to(device)
print('number of par is',sum([p.numel() for p in denoise.parameters()]))
print('number of par is by calc is',N*d+100*N)
optimizer = torch.optim.Adam(denoise.parameters())

print(denoise)

denoise.lin1.weight.requires_grad = False
denoise.lin1.bias.requires_grad = False

n_epochs = 20
batch_size = 50
for step in range(n_epochs):
  # perm = torch.randperm()
  # for j in range(n_steps):
    optimizer.zero_grad()
    t = torch.randint(0, n_steps, (batch_size,)).to(device)  # Pick random time step
    loss = p_loss(x0, t)
    loss.backward()
    if step % (n_epochs // 10) == 0:
        # print(torch.norm(denoise.lin.weight.detach()))
        print(f"loss={loss.item():.4f};") # a={denoise.a.item():.4f}, b={denoise.b.item():.4f}, c={denoise.c.item():.4f}")
    optimizer.step()
# print(f"final: loss={loss.item():.4f}; a={denoise.a.item():.4f}, b={denoise.b.item():.4f}, c={denoise.c.item():.4f}")


alphas_cumprod_prev = F.pad(alphas_cumprod[:-1], (1, 0), value=1.0)
posterior_variance = ((1 - alphas) * (1. - alphas_cumprod_prev) / (1. - alphas_cumprod))

def p_sample(x, t):
    """
    One step of revese process sampling - Algorithm 2 from the paper
    """
    if t!=0:
      alpha_t = alphas.cpu().gather(-1, t.cpu()).repeat(d,1).T
      sqrt_one_minus_alphas_cumprod_t = sqrt_one_minus_alphas_cumprod.cpu().gather(-1, t.cpu()).repeat(d,1).T
      # Get mean x[t - 1] conditioned at x[t] - see eq. (11) in the paper
      model_mean = torch.sqrt(1.0 / alpha_t) * (x - (1 - alpha_t) * denoise(x.float().to(device), t.reshape(-1,1).to(device)).cpu() / sqrt_one_minus_alphas_cumprod_t)
      # Get variance of x[t - 1]
      model_var = posterior_variance.cpu().gather(-1, t.cpu()).repeat(d,1).T
      # Samples for the normal distribution with given mean and variance
    else:
      model_var = 0
    return model_mean + torch.sqrt(model_var) * torch.randn(d)



# Create a sample of 10000 "noisy" datapoint at time t = 100
# x_gen = torch.randn((1,1,d))

k=1
D = d
Z = np.zeros((k,D))
Z_init = np.zeros((k,D))
for j in range(k):
  x_gen = torch.randn((1,1,D))
    # x_gen = 0.8*(torch.Tensor(data[15,:]))+ 0.2*torch.randn((1,1,D))

  Z_init[j,:] = x_gen.detach().numpy().reshape(-1)
  # plt.imshow(Z_init[j,:].reshape(28,28))

  for i in range(n_steps - 1, 0, -1):
      # denoise the sample step by step backawards in time
      x_gen = p_sample(x_gen.detach(), torch.tensor(i))
  Z[j,:] = x_gen.detach().numpy().reshape(-1)

plt.figure(figsize=(10,10))
for i in range(k):
  plt.subplot(1,5,i+1)
  plt.plot(Z_init[i,:],'.')

plt.figure(figsize=(10,10))
for i in range(k):
  plt.subplot(1,5,i+1)
  plt.plot(Z[i,:],'.')


Audio(Z[0,:],rate=sr)

# from numpy import savetxt
# savetxt('data_gen_rfm.csv', Z, delimiter=',')

# plt.figure(figsize=(10,10))
# for i in range(k):
#   plt.subplot(2,5,i+1)
#   # plt.plot(Z_init[i,:],'.')
#   plt.imshow(Z[i,:].reshape(30,30),cmap=plt.cm.gray)



